package ballmerpeak.stargate;

public enum InputCommand {
	
	UP_COMMAND, DOWN_COMMAND, LEFT_COMMAND, RIGHT_COMMAND,
	
	PICKUP_COMMAND, SHOOT_YELLOW_COMMAND, SHOOT_BLUE_COMMAND,
	
	QUIT_COMMAND,
	
	UNKNOWN_COMMAND

}
