package ballmerpeak.stargate.gui;

public enum DrawableIndex {
	FLOOR, FLOOR_WITH_ZPM, FLOOR_WITH_CRATE,
	
	SCALE, SCALE_WITH_CRATE, DOOR_CLOSED, DOOR_OPEN,
	
	WALL, SPECIAL_WALL_INACTIVE, SPECIAL_WALL_YELLOW, SPECIAL_WALL_BLUE,
	
	PIT,
	
	PLAYER_FACING_LEFT, PLAYER_FACING_RIGHT, PLAYER_FACING_UP, PLAYER_FACING_DOWN,
	
	ASSETCOUNT
}
